env:
  MAVEN_ARGS: -V -B --no-transfer-progress -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
jobs:
  linux:
    name: Linux JDK 11
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Test
      run: ./mvnw ${MAVEN_ARGS} install
    - continue-on-error: true
      name: Generate coverage report
      run: ./mvnw jacoco:report
    - continue-on-error: true
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
    - continue-on-error: true
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository
        == 'mapstruct/mapstruct'
      name: Publish Snapshots
      run: ./mvnw -s etc/ci-settings.xml -DskipTests=true -DskipDistribution=true
        deploy
  linux-jdk-8:
    name: Linux JDK 8
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11 for building everything
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Install Processor
      run: ./mvnw ${MAVEN_ARGS} -DskipTests install -pl processor -am
    - continue-on-error: true
      name: Set up JDK 8 for running integration tests
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      name: Run integration tests
      run: ./mvnw ${MAVEN_ARGS} verify -pl integrationtest
  mac:
    name: Mac OS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Test
      run: ./mvnw ${MAVEN_ARGS} install
  test_jdk:
    name: Linux JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test
      run: ./mvnw ${MAVEN_ARGS} -Djacoco.skip=true install -DskipDistribution=true
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
        - 21
  windows:
    name: Windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Test
      run: ./mvnw %MAVEN_ARGS% install
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
